name: 3ML
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=h5bd9786_13
  - afterimage=1.21=ha9998ff_1003
  - algopy=0.5.7=py_0
  - alsa-lib=1.2.8=h166bdaf_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=3.6.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb9d737c_3
  - arrow-cpp=9.0.0=py39hb256316_16_cpu
  - asciitree=0.3.3=py_2
  - astromodels=2.3.9=py39hac2352c_0
  - astropy=5.2.2=py39hf0d0a58_0
  - astropy-healpix=0.7=py39h2ae25f5_2
  - astroquery=0.4.6=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd4edc92_1
  - attr=2.5.1=h166bdaf_1
  - attrs=22.2.0=pyh71513ae_0
  - aws-c-auth=0.6.21=hd93a3ba_3
  - aws-c-cal=0.5.20=hd3b2fe5_3
  - aws-c-common=0.8.5=h166bdaf_0
  - aws-c-compression=0.2.16=hf5f93bc_0
  - aws-c-event-stream=0.2.17=h57874a7_1
  - aws-c-http=0.7.0=h96ef541_0
  - aws-c-io=0.13.12=h57ca295_1
  - aws-c-mqtt=0.7.13=h0b5698f_12
  - aws-c-s3=0.2.1=h5d7e488_4
  - aws-c-sdkutils=0.1.7=hf5f93bc_0
  - aws-checksums=0.1.14=h6027aba_0
  - aws-crt-cpp=0.18.16=h26430d7_8
  - aws-sdk-cpp=1.9.379=h56135f1_7
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.1=pyha770c72_0
  - binutils=2.39=hdd6e379_1
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_12
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.3=hafa529b_0
  - bokeh=3.2.2=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-compiler=1.5.1=h166bdaf_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_3
  - cfitsio=4.1.0=hd9d235c_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - compilers=1.5.1=ha770c72_0
  - contourpy=1.0.7=py39h4b4f3f3_0
  - corner=2.1.0=pyhd3deb0d_1
  - cryptography=39.0.0=py39hd598818_0
  - cxx-compiler=1.5.1=h924138e_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.2=py39hd1e30aa_0
  - dask=2023.9.1=pyhd8ed1ab_0
  - dask-core=2023.9.1=pyhd8ed1ab_0
  - davix=0.8.3=h7666a67_1
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.7=py39h227be39_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - distributed=2023.9.1=pyhd8ed1ab_0
  - dynesty=2.1.0=pyhd8ed1ab_0
  - emcee=3.1.4=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.3=py39h72bdee0_0
  - fortran-compiler=1.5.1=h2a4ca65_0
  - freetype=2.12.1=hca18f0e_1
  - fribidi=1.0.10=h36c2ea0_0
  - fsspec=2023.9.0=pyh1a96a4e_0
  - ftgl=2.4.0=hbcb1f35_0
  - future=0.18.3=pyhd8ed1ab_0
  - gammapy=1.0.1=py39h389d5f1_0
  - gcc=10.4.0=hb92f740_12
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - gcc_linux-64=10.4.0=h9215b83_12
  - gdk-pixbuf=2.42.8=hff1cb4f_1
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - gfortran=10.4.0=h0c96582_12
  - gfortran_impl_linux-64=10.4.0=h7d168d2_19
  - gfortran_linux-64=10.4.0=h69d5af5_12
  - giflib=5.2.1=h0b41bf4_3
  - gl2ps=1.4.2=h0708190_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.74.1=h6239696_1
  - glib-tools=2.74.1=h6239696_1
  - glog=0.6.0=h6f12383_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=3.0.0=h5abf519_2
  - gsl=2.7=he838d99_0
  - gsoap=2.8.123=h598caef_0
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.33=h166bdaf_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h64030ff_2
  - gxx=10.4.0=hb92f740_12
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - gxx_linux-64=10.4.0=h6e491c6_12
  - h5py=3.8.0=nompi_py39h89bf01e_101
  - harfbuzz=6.0.0=h8e241bc_0
  - hdf5=1.14.0=nompi_h5231ba7_103
  - healpy=1.16.1=py39hbafa5a2_2
  - html5lib=1.1=pyh9f0ad1d_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - iminuit=2.21.3=py39h227be39_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - importlib-resources=5.12.0=pyhd8ed1ab_0
  - importlib_metadata=6.1.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - interpolation=2.2.3=pyhd8ed1ab_1
  - ipykernel=6.22.0=pyh210e3f2_0
  - ipyparallel=8.5.1=pyhd8ed1ab_0
  - ipython=8.12.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.6=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jaraco.classes=3.2.3=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h0b41bf4_3
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.1.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39hf3d152e_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.7=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=h4a8ded7_13
  - keyring=23.13.1=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_1
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.0.6=hcb278e6_1
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.7=default_had23c3d_1
  - libclang13=15.0.7=default_h3e3d535_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=h6312ad2_0
  - libcxx=13.0.1=hf52228f_0
  - libcxxabi=13.0.1=ha770c72_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgcrypt=1.10.1=h166bdaf_0
  - libgd=2.3.3=h18fbbfe_3
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h606061b_1
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.2.0=h65d4601_19
  - libgoogle-cloud=2.5.0=h5d50b59_1
  - libgpg-error=1.46=h620e276_0
  - libgrpc=1.51.1=h05bd8bd_0
  - libhwloc=2.9.0=hd6dc26d_0
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libllvm15=15.0.7=hadd5161_1
  - libllvm9=9.0.1=default_hc23dcda_7
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.1=h2baec63_3
  - libprotobuf=3.21.12=hfc55251_2
  - librsvg=2.54.4=h7abd40a_0
  - libsanitizer=10.4.0=h5246dfb_19
  - libsndfile=1.2.0=hb75c966_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libsystemd0=252=h2a991cd_0
  - libthrift=0.16.0=h491838f_2
  - libtiff=4.4.0=h82bc61c_5
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h166bdaf_4
  - llvmlite=0.39.1=py39h7d9a04d_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.2=py39h724f13c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - markdown-it-py=2.2.0=pyhd8ed1ab_0
  - markupsafe=2.1.2=py39h72bdee0_0
  - matplotlib=3.7.1=py39hf3d152e_0
  - matplotlib-base=3.7.1=py39he190548_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - metakernel=0.29.4=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - more-itertools=9.1.0=pyhd8ed1ab_0
  - mpg123=1.31.3=hcb278e6_0
  - msgpack-python=1.0.5=py39h4b4f3f3_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - nbclassic=0.5.5=pyh8b2e9e2_0
  - nbclient=0.7.3=pyhd8ed1ab_0
  - nbconvert-core=7.3.0=pyhd8ed1ab_2
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nlohmann_json=3.10.5=h27087fc_1
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.89=he45b914_0
  - numba=0.56.4=py39h61ddf18_0
  - numcodecs=0.11.0=py39h227be39_1
  - numdifftools=0.9.41=pyhd8ed1ab_0
  - numexpr=2.8.4=py39h5ef5dce_100
  - numpy=1.23.5=py39h3d75532_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1v=hd590300_0
  - orc=1.8.2=hfdbbad2_2
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=2.0.0=py39h2ad29b5_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=hd33c08f_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.4.0=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hf3a2cdf_3
  - pip=23.2.1=py39h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - pluggy=1.0.0=pyhd8ed1ab_5
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - portalocker=2.7.0=py39hf3d152e_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=h4ab2085_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=9.0.0=py39hacc6ce7_16_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.7=py39h72bdee0_0
  - pyerfa=2.0.0.3=py39h389d5f1_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h5c7b992_3
  - pyqt5-sip=12.11.0=py39h227be39_3
  - pyrsistent=0.19.3=py39h72bdee0_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.7.0=py39hf8baa48_4
  - pytest=7.2.2=pyhd8ed1ab_0
  - pytest-runner=6.0.0=pyhd8ed1ab_0
  - pythia8=8.307=py39h5a03fae_0
  - python=3.9.15=h47a2c10_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2023.3=pyhd8ed1ab_0
  - pyvo=1.4.1=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_5
  - pyzmq=25.0.2=py39h0be026e_0
  - qt-main=5.15.6=h18908ee_6
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - regions=0.7=py39h2ae25f5_2
  - reproject=0.12.0=py39h44dd56e_0
  - requests=2.28.2=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.3.3=pyhd8ed1ab_0
  - root=6.24.6=py39h1832856_3
  - root_base=6.24.6=py39h9749efa_3
  - root_numpy=4.8.0=py39h76aeced_16
  - s2n=1.3.31=hae46d1a_0
  - scipy=1.10.1=py39h7360e5f_0
  - scitokens-cpp=0.7.1=h0255ffa_0
  - secretstorage=3.3.3=py39hf3d152e_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.6.1=pyhd8ed1ab_0
  - sip=6.7.7=py39h227be39_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - speclite=0.14=py39hf3d152e_0
  - sqlite=3.40.0=h4ff8645_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py39h2ae25f5_2
  - sysroot_linux-64=2.17=h4a8ded7_13
  - tbb=2021.8.0=hf52228f_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tempita=0.5.3dev=py39hf3d152e_1002
  - terminado=0.17.1=pyh41d4057_0
  - threeml=2.4.0=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py39hb9d737c_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - uncertainties=3.1.7=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - vdt=0.4.3=h9c3ff4c_0
  - vector-classes=1.4.2=h4bd325d_1
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.7=pyhd8ed1ab_0
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.6.12=h36c2ea0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxcursor=1.2.0=h516909a_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxft=2.3.4=hc534e41_1
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xrootd=5.5.1=py39h765a0e5_3
  - xxhash=0.8.0=h7f98852_3
  - xyzservices=2023.7.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zarr=2.16.1=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h3eb15da_6
prefix: /data/home/cwy/.mylib/miniconda3/envs/3ML
